# Uncomment the next line to define a global platform for your project


target 'Diet Science' do
  platform :ios, '13.4'

  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Diet Science
  pod 'Apollo'
  pod 'PromisesSwift'
  pod 'Auth0', '~> 1.0'

  target 'Diet ScienceTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Diet ScienceUITests' do
    # Pods for testing
  end

end

target 'Diet Science WatchKit App' do
  platform :watchos, '6.2'

  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Diet Science WatchKit App
  pod 'Apollo'
  pod 'PromisesSwift'
  pod 'Auth0', '~> 1.0'

end

target 'Diet Science WatchKit Extension' do
  platform :watchos, '6.2'

  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Diet Science WatchKit Extension
  pod 'Apollo'
  pod 'PromisesSwift'
  pod 'Auth0', '~> 1.0'

end
